# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pyramidage.ui'
#
# Created: Wed Jan 16 16:32:26 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import datetime

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_pyramidAgeDialog(object):
    def setupUi(self, pyramidAgeDialog):
        pyramidAgeDialog.setObjectName(_fromUtf8("pyramidAgeDialog"))
        pyramidAgeDialog.resize(721, 752)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pyramidAgeDialog.sizePolicy().hasHeightForWidth())
        pyramidAgeDialog.setSizePolicy(sizePolicy)
        pyramidAgeDialog.setMinimumSize(QtCore.QSize(100, 100))
        pyramidAgeDialog.setSizeIncrement(QtCore.QSize(0, 0))
        pyramidAgeDialog.setBaseSize(QtCore.QSize(0, 0))
        self.layoutWidget = QtGui.QWidget(pyramidAgeDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 711, 735))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout.setMargin(20)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chooseTextFileButton = QtGui.QPushButton(self.layoutWidget)
        self.chooseTextFileButton.setObjectName(_fromUtf8("chooseTextFileButton"))
        self.horizontalLayout.addWidget(self.chooseTextFileButton)
        self.textFileLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.textFileLineEdit.setObjectName(_fromUtf8("textFileLineEdit"))
        self.horizontalLayout.addWidget(self.textFileLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setMargin(0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.anneeLabel = QtGui.QLabel(self.layoutWidget)
        self.anneeLabel.setObjectName(_fromUtf8("anneeLabel"))
        self.gridLayout.addWidget(self.anneeLabel, 0, 0, 1, 1)
        self.anneeSpinBox = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anneeSpinBox.sizePolicy().hasHeightForWidth())
        self.anneeSpinBox.setSizePolicy(sizePolicy)
        self.anneeSpinBox.setMinimum(-9999)
        self.anneeSpinBox.setMaximum(9999)
        self.anneeSpinBox.setProperty("value", 2000)
        self.anneeSpinBox.setObjectName(_fromUtf8("anneeSpinBox"))
        self.gridLayout.addWidget(self.anneeSpinBox, 0, 1, 1, 1)
        self.anneeNaissLabel = QtGui.QLabel(self.layoutWidget)
        self.anneeNaissLabel.setObjectName(_fromUtf8("anneeNaissLabel"))
        self.gridLayout.addWidget(self.anneeNaissLabel, 0, 3, 1, 1)
        self.anneeNaissComboBox = QtGui.QComboBox(self.layoutWidget)
        self.anneeNaissComboBox.setObjectName(_fromUtf8("anneeNaissComboBox"))
        self.gridLayout.addWidget(self.anneeNaissComboBox, 0, 4, 1, 1)
        self.carDelLabel = QtGui.QLabel(self.layoutWidget)
        self.carDelLabel.setObjectName(_fromUtf8("carDelLabel"))
        self.gridLayout.addWidget(self.carDelLabel, 1, 0, 1, 1)
        self.carDelComboBox = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carDelComboBox.sizePolicy().hasHeightForWidth())
        self.carDelComboBox.setSizePolicy(sizePolicy)
        self.carDelComboBox.setObjectName(_fromUtf8("carDelComboBox"))
        self.carDelComboBox.addItem(_fromUtf8(""))
        self.carDelComboBox.addItem(_fromUtf8(""))
        self.carDelComboBox.addItem(_fromUtf8(""))
        self.carDelComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.carDelComboBox, 1, 1, 1, 1)
        self.sexeLabel = QtGui.QLabel(self.layoutWidget)
        self.sexeLabel.setObjectName(_fromUtf8("sexeLabel"))
        self.gridLayout.addWidget(self.sexeLabel, 1, 3, 1, 1)
        self.sexeComboBox = QtGui.QComboBox(self.layoutWidget)
        self.sexeComboBox.setObjectName(_fromUtf8("sexeComboBox"))
        self.gridLayout.addWidget(self.sexeComboBox, 1, 4, 1, 1)
        self.tailleClasseLabel = QtGui.QLabel(self.layoutWidget)
        self.tailleClasseLabel.setObjectName(_fromUtf8("tailleClasseLabel"))
        self.gridLayout.addWidget(self.tailleClasseLabel, 2, 0, 1, 1)
        self.tailleClasseSpinBox = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tailleClasseSpinBox.sizePolicy().hasHeightForWidth())
        self.tailleClasseSpinBox.setSizePolicy(sizePolicy)
        self.tailleClasseSpinBox.setMinimum(1)
        self.tailleClasseSpinBox.setProperty("value", 5)
        self.tailleClasseSpinBox.setObjectName(_fromUtf8("tailleClasseSpinBox"))
        self.gridLayout.addWidget(self.tailleClasseSpinBox, 2, 1, 1, 1)
        self.statutLabel = QtGui.QLabel(self.layoutWidget)
        self.statutLabel.setObjectName(_fromUtf8("statutLabel"))
        self.gridLayout.addWidget(self.statutLabel, 2, 3, 1, 1)
        self.statutComboBox = QtGui.QComboBox(self.layoutWidget)
        self.statutComboBox.setObjectName(_fromUtf8("statutComboBox"))
        self.gridLayout.addWidget(self.statutComboBox, 2, 4, 1, 1)
        self.debClasseLabel = QtGui.QLabel(self.layoutWidget)
        self.debClasseLabel.setObjectName(_fromUtf8("debClasseLabel"))
        self.gridLayout.addWidget(self.debClasseLabel, 3, 0, 1, 1)
        self.debClasseSpinBox = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.debClasseSpinBox.sizePolicy().hasHeightForWidth())
        self.debClasseSpinBox.setSizePolicy(sizePolicy)
        self.debClasseSpinBox.setMinimum(1)
        self.debClasseSpinBox.setProperty("value", 30)
        self.debClasseSpinBox.setObjectName(_fromUtf8("debClasseSpinBox"))
        self.gridLayout.addWidget(self.debClasseSpinBox, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.finClasseLabel = QtGui.QLabel(self.layoutWidget)
        self.finClasseLabel.setObjectName(_fromUtf8("finClasseLabel"))
        self.gridLayout.addWidget(self.finClasseLabel, 4, 0, 1, 1)
        self.finClasseComboBox = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finClasseComboBox.sizePolicy().hasHeightForWidth())
        self.finClasseComboBox.setSizePolicy(sizePolicy)
        self.finClasseComboBox.setObjectName(_fromUtf8("finClasseComboBox"))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.finClasseComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.finClasseComboBox, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.formLayout.setLayout(1, QtGui.QFormLayout.SpanningRole, self.verticalLayout)
        spacerItem1 = QtGui.QSpacerItem(661, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtGui.QFormLayout.SpanningRole, spacerItem1)
        self.choixStatutsLabel = QtGui.QLabel(self.layoutWidget)
        self.choixStatutsLabel.setObjectName(_fromUtf8("choixStatutsLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.choixStatutsLabel)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.statutTableWidget = QtGui.QTableWidget(self.layoutWidget)
        self.statutTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.statutTableWidget.setObjectName(_fromUtf8("statutTableWidget"))
        self.statutTableWidget.setColumnCount(2)
        self.statutTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.statutTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.statutTableWidget.setHorizontalHeaderItem(1, item)
        self.statutTableWidget.horizontalHeader().setVisible(True)
        self.statutTableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.horizontalLayout_3.addWidget(self.statutTableWidget)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.addStatutPushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addStatutPushButton.sizePolicy().hasHeightForWidth())
        self.addStatutPushButton.setSizePolicy(sizePolicy)
        self.addStatutPushButton.setObjectName(_fromUtf8("addStatutPushButton"))
        self.verticalLayout_2.addWidget(self.addStatutPushButton)
        self.removeStatutPushButton = QtGui.QPushButton(self.layoutWidget)
        self.removeStatutPushButton.setObjectName(_fromUtf8("removeStatutPushButton"))
        self.verticalLayout_2.addWidget(self.removeStatutPushButton)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.formLayout.setLayout(4, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_3)
        spacerItem3 = QtGui.QSpacerItem(666, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtGui.QFormLayout.SpanningRole, spacerItem3)
        self.apercuLabel = QtGui.QLabel(self.layoutWidget)
        self.apercuLabel.setObjectName(_fromUtf8("apercuLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.apercuLabel)
        self.apercuTableWidget = QtGui.QTableWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apercuTableWidget.sizePolicy().hasHeightForWidth())
        self.apercuTableWidget.setSizePolicy(sizePolicy)
        self.apercuTableWidget.setMinimumSize(QtCore.QSize(661, 0))
        self.apercuTableWidget.setAlternatingRowColors(True)
        self.apercuTableWidget.setShowGrid(True)
        self.apercuTableWidget.setObjectName(_fromUtf8("apercuTableWidget"))
        self.apercuTableWidget.setColumnCount(0)
        self.apercuTableWidget.setRowCount(0)
        self.formLayout.setWidget(7, QtGui.QFormLayout.SpanningRole, self.apercuTableWidget)
        spacerItem4 = QtGui.QSpacerItem(505, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtGui.QFormLayout.FieldRole, spacerItem4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem5 = QtGui.QSpacerItem(485, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.quitButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quitButton.sizePolicy().hasHeightForWidth())
        self.quitButton.setSizePolicy(sizePolicy)
        self.quitButton.setMinimumSize(QtCore.QSize(85, 27))
        self.quitButton.setObjectName(_fromUtf8("quitButton"))
        self.horizontalLayout_2.addWidget(self.quitButton)
        self.okButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setMinimumSize(QtCore.QSize(85, 27))
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.horizontalLayout_2.addWidget(self.okButton)
        self.formLayout.setLayout(9, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_2)

        self.retranslateUi(pyramidAgeDialog)
        self.finClasseComboBox.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(pyramidAgeDialog)

    def retranslateUi(self, pyramidAgeDialog):
        pyramidAgeDialog.setWindowTitle(QtGui.QApplication.translate("pyramidAgeDialog", "Pyramidage", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseTextFileButton.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Sélectionner le fichier texte contenant les données de la pyramide des âges", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseTextFileButton.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Choisir le fichier texte", None, QtGui.QApplication.UnicodeUTF8))
        self.anneeLabel.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Année", None, QtGui.QApplication.UnicodeUTF8))
        self.anneeSpinBox.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Année en cours", None, QtGui.QApplication.UnicodeUTF8))
        self.anneeNaissLabel.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Champ année de naissance", None, QtGui.QApplication.UnicodeUTF8))
        self.anneeNaissComboBox.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Colonne du fichier texte contenant les années de naissance", None, QtGui.QApplication.UnicodeUTF8))
        self.carDelLabel.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Caractère délimiteur", None, QtGui.QApplication.UnicodeUTF8))
        self.carDelComboBox.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Caractère séparant les colonnes dans le fichier texte", None, QtGui.QApplication.UnicodeUTF8))
        self.carDelComboBox.setItemText(0, QtGui.QApplication.translate("pyramidAgeDialog", "Tabulation", None, QtGui.QApplication.UnicodeUTF8))
        self.carDelComboBox.setItemText(1, QtGui.QApplication.translate("pyramidAgeDialog", "Point-virgule", None, QtGui.QApplication.UnicodeUTF8))
        self.carDelComboBox.setItemText(2, QtGui.QApplication.translate("pyramidAgeDialog", "Virgule", None, QtGui.QApplication.UnicodeUTF8))
        self.carDelComboBox.setItemText(3, QtGui.QApplication.translate("pyramidAgeDialog", "Espace", None, QtGui.QApplication.UnicodeUTF8))
        self.sexeLabel.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Champ sexe", None, QtGui.QApplication.UnicodeUTF8))
        self.sexeComboBox.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Colonne du fichier texte contenant le sexe : F pour femme, H pour homme", None, QtGui.QApplication.UnicodeUTF8))
        self.tailleClasseLabel.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Taille d\'une classe d\'âge", None, QtGui.QApplication.UnicodeUTF8))
        self.tailleClasseSpinBox.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Taille d\'une classe d\'âge", None, QtGui.QApplication.UnicodeUTF8))
        self.statutLabel.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Champ statut", None, QtGui.QApplication.UnicodeUTF8))
        self.statutComboBox.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Colonne du fichier texte contenant les différents statuts", None, QtGui.QApplication.UnicodeUTF8))
        self.debClasseLabel.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Début de la première classe d\'âge", None, QtGui.QApplication.UnicodeUTF8))
        self.debClasseSpinBox.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Début de la 1ère classe d\'âge", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseLabel.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Fin de la dernière classe d\'âge", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Fin de la dernière classe d\'âge", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(0, QtGui.QApplication.translate("pyramidAgeDialog", "35", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(1, QtGui.QApplication.translate("pyramidAgeDialog", "40", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(2, QtGui.QApplication.translate("pyramidAgeDialog", "45", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(3, QtGui.QApplication.translate("pyramidAgeDialog", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(4, QtGui.QApplication.translate("pyramidAgeDialog", "55", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(5, QtGui.QApplication.translate("pyramidAgeDialog", "60", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(6, QtGui.QApplication.translate("pyramidAgeDialog", "65", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(7, QtGui.QApplication.translate("pyramidAgeDialog", "70", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(8, QtGui.QApplication.translate("pyramidAgeDialog", "75", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(9, QtGui.QApplication.translate("pyramidAgeDialog", "80", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(10, QtGui.QApplication.translate("pyramidAgeDialog", "85", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(11, QtGui.QApplication.translate("pyramidAgeDialog", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(12, QtGui.QApplication.translate("pyramidAgeDialog", "95", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(13, QtGui.QApplication.translate("pyramidAgeDialog", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(14, QtGui.QApplication.translate("pyramidAgeDialog", "105", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(15, QtGui.QApplication.translate("pyramidAgeDialog", "110", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(16, QtGui.QApplication.translate("pyramidAgeDialog", "115", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(17, QtGui.QApplication.translate("pyramidAgeDialog", "120", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(18, QtGui.QApplication.translate("pyramidAgeDialog", "125", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(19, QtGui.QApplication.translate("pyramidAgeDialog", "130", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(20, QtGui.QApplication.translate("pyramidAgeDialog", "135", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(21, QtGui.QApplication.translate("pyramidAgeDialog", "140", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(22, QtGui.QApplication.translate("pyramidAgeDialog", "145", None, QtGui.QApplication.UnicodeUTF8))
        self.finClasseComboBox.setItemText(23, QtGui.QApplication.translate("pyramidAgeDialog", "150", None, QtGui.QApplication.UnicodeUTF8))
        self.choixStatutsLabel.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Choisissez les statuts à représenter et leur couleur :", None, QtGui.QApplication.UnicodeUTF8))
        self.statutTableWidget.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Liste des statuts qui seront pris en compte pour dessiner la pyramide des âges", None, QtGui.QApplication.UnicodeUTF8))
        item = self.statutTableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Statut", None, QtGui.QApplication.UnicodeUTF8))
        item = self.statutTableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Couleur", None, QtGui.QApplication.UnicodeUTF8))
        self.addStatutPushButton.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Prendre en compte un statut supplémentaire", None, QtGui.QApplication.UnicodeUTF8))
        self.addStatutPushButton.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Ajouter un statut", None, QtGui.QApplication.UnicodeUTF8))
        self.removeStatutPushButton.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Supprimer la ligne du tableau sélectionnée", None, QtGui.QApplication.UnicodeUTF8))
        self.removeStatutPushButton.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Supprimer un statut", None, QtGui.QApplication.UnicodeUTF8))
        self.apercuLabel.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Aperçu du fichier texte :", None, QtGui.QApplication.UnicodeUTF8))
        self.apercuTableWidget.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Aperçu des données du fichier texte, en fonction du caractère délimiteur choisi", None, QtGui.QApplication.UnicodeUTF8))
        self.quitButton.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Quitter l\'application sans dessiner de pyramide des âges", None, QtGui.QApplication.UnicodeUTF8))
        self.quitButton.setText(QtGui.QApplication.translate("pyramidAgeDialog", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setToolTip(QtGui.QApplication.translate("pyramidAgeDialog", "Dessiner une nouvelle pyramide des âges", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("pyramidAgeDialog", "OK", None, QtGui.QApplication.UnicodeUTF8))

